name: "Build and push to ECR"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-ecr:
    name: "Build and Push to ECR"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Download bloom filter
        run: |
          cd database
          curl -OL https://s3.ap-southeast-1.amazonaws.com/hibp.saveoursecrets.com/last-updated.txt
          curl -OL https://s3.ap-southeast-1.amazonaws.com/hibp.saveoursecrets.com/hibp.bloom

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "hashcheck"
          IMAGE_TAG: ${{github.ref_name}}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
